"""A file for storing configuration text. 
It's easier than parsing a text file."""
FONT_TYPE = "Arial"

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

START_SCORE = 0
START_LIVES = 3

START_PRESENT_SIZE = 5.0
PRESENT_SIZE_INCREMENT = 0.5
MIN_PRESENT_SIZE = 0.3

START_PRESENT_AMOUNT = 3
PRESENT_AMOUNT_INCREMENT = 2

START_PRESENT_WORTH = 5
PRESENT_WORTH_INCREMENT = 10

PLAYER_START = (100,100)

PLAYER_START_SPEED = 10
PLAYER_SPEED_INCREMENT = 20
MAX_PLAYER_SPEED = 300

START_TIME = 30
START_TIME += 2 #For some reason it starts with two seconds off
TIME_INCREMENT = 2

PLAYER_STEPS = 100
